FROM python:3.11


ENV PYTHONUNBUFFERED 1
ENV APP_HOME=/app


WORKDIR $APP_HOME


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . $APP_HOME


CMD ["python", "ingest.py"]